[package]
name = "myrrh-rs"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2.8", features = ["derive"] }
anyhow = "1.0"
tracing = "0.1.35"
tracing-subscriber = "0.3.12"
serde_json = "1.0"
regex = "1"
itertools = "0.10.5"
json = "0.12.4"
rand = "0.8.5"